#!/bin/bash

<<"COMMENTS"
Copyright © 2020 Nicolle Rémi

This file is part of OpenScripts.

OpenScripts is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenScripts is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenScripts.  If not, see <https://www.gnu.org/licenses/>.
COMMENTS

if [ $# != 1 ]
then
    Echo "You must specify exactly 1 parameter" red default false
    exit 1
fi

if [ -d $1 ]
then
    find $1 -name gmon.out -type f -exec rm {} \;
else
    Echo "You must specify a valid directory for parameter one." red default false
    exit 2
fi

exit 0

