#!/bin/bash

<<"COMMENTS"
Copyright © 2020 Nicolle Rémi

This file is part of OpenScripts.

OpenScripts is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenScripts is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenScripts.  If not, see <https://www.gnu.org/licenses/>.
COMMENTS

Type=true
Ret=false

declare -A colors

colors=([black]=0 [red]=1 [green]=2 [yellow]=3 [blue]=4 [magenta]=5 [cyan]=6 [white]=7 [default]=8)


if [ "$#" -ne 4 ]
then
    if [ "$#" -ne 3 ]
    then
        echo "You must specify 3 or 2 parameters."
        exit 1
    fi
else
    if [ $4 = true ]
    then
        Type=true
    elif [ $4 = false ]
    then
        Type=false
    else
        echo "The third parameter must be boolean."
        exit 2
    fi
fi

for color in "${!colors[@]}"; do
    if [ $2 = $color ]; then
        Ret=true
    fi
done

if [ $Ret != true ]; then
    echo "Foreground color is invalid."
    exit 3
fi

for color in "${!colors[@]}"; do
    if [ $3 = $color ]; then
        Ret=true
    fi
done

if [ $Ret != true ]; then
    echo "Background color is invalid."
    exit 4
fi

if [ $2 != default ]
then
    tput setaf ${colors[$2]}
fi

if [ $3 != default ]
then
    tput setab ${colors[$3]}
fi

if [ $Type = true ]
then
    echo -e "$1\c"
else
    echo -e "$1"
fi

tput sgr0

exit 0

