#!/bin/bash

<<"COMMENTS"
Copyright © 2020 Nicolle Rémi

This file is part of OpenScripts.

OpenScripts is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

OpenScripts is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with OpenScripts.  If not, see <https://www.gnu.org/licenses/>.
COMMENTS

Type="module"

if [ $# != 2 ]
then
    Echo "You must specify exactly 2 parameters." red default false
    exit 1
fi

case $1 in
    "making" | "clean" | "install" | "module" | "static" | "dynamic" | "program_s" | "program_d" | "doc") Type=$1;;
    *) Echo "Type parameter is invalid" red default false
       exit 2;;
esac

case $Type in
    "making") Echo "Making $2" red default false;;
    "clean") Echo "Cleaning $2" red default false;;
    "install") Echo "Installing $2" red default false;;
    "module") Echo "... Compile module `Spaces 9` $2" green default false;;
    "static") Echo "==> Creating static lib `Spaces 4` $2" blue default false;;
    "dynamic") Echo "==> Creating dynamic lib `Spaces 3` $2" cyan default false;;
    "program_s") Echo "==> Linking static `Spaces 9` $2" magenta default false;;
    "program_d") Echo "==> Linking static `Spaces 9` $2" magenta default false;;
    "doc") Echo "... Compiling doc: $2" yellow default false;;
esac

exit 0

